name: Format and Lint Python

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff
      run: ruff check . --fix

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Format code with Ruff'
      continue-on-error: true

    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 
